# version: '3.8'

# services:
#   redis:
#     image: redis:latest
#     container_name: url_shortener
#     restart: always
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     env_file:
#       - .env
#     command: ["redis-server", "--requirepass", "$REDIS_PASSWORD", "--appendonly", "yes"]

# volumes:
#   redis_data:
#     driver: local


version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    restart: always
    depends_on:
      - redis
    env_file:
      - .env  # Loads environment variables from .env file
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    container_name: url_shortener
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local
